import type { FastifyPluginAsync } from 'fastify';
import {
  getAuthorizationUrl,
  exchangeCodeForTokens,
  getZoomUserProfile,
} from '@zoom-assistant/zoom';
import {
  userRepo,
  zoomAccountRepo,
  oauthStateRepo,
  auditRepo,
} from '@zoom-assistant/database';
import { encryptToken } from '@zoom-assistant/crypto';
import { createLogger } from '@zoom-assistant/shared';

const log = createLogger({ module: 'oauth-routes' });

export const oauthRoutes: FastifyPluginAsync = async (fastify) => {
  /**
   * GET /zoom/connect?telegram_user_id=123456789
   * GET /auth/zoom/connect?telegram_user_id=123456789
   */
  fastify.get('/zoom/connect', async (request, reply) => {
    return handleConnect(request, reply);
  });
  fastify.get('/auth/zoom/connect', async (request, reply) => {
    return handleConnect(request, reply);
  });

  async function handleConnect(request: any, reply: any) {
    const query = request.query as { telegram_user_id?: string };
    const telegramUserIdStr = query.telegram_user_id;

    if (!telegramUserIdStr) {
      return reply.status(400).send('Missing telegram_user_id parameter');
    }

    const clientId = process.env['ZOOM_CLIENT_ID'] ?? '';
    const redirectUri =
      process.env['ZOOM_REDIRECT_URI'] ?? 'https://ai-zoom-participant.onrender.com/auth/zoom/callback';

    let state = telegramUserIdStr;
    try {
      const telegramUserId = BigInt(telegramUserIdStr);
      await userRepo.upsert(telegramUserId).catch(() => {});
      const createdState = await oauthStateRepo.create(telegramUserId).catch(() => null);
      if (createdState) {
        state = createdState;
      }
    } catch (err: any) {
      log.warn({ error: err.message }, 'OAuth state storage warning (using fallback state)');
    }

    const authUrl = getAuthorizationUrl(clientId, redirectUri, state);
    log.info({ telegramUserId: telegramUserIdStr, authUrl }, 'Initiating Zoom OAuth redirect');

    return reply.redirect(authUrl);
  }

  fastify.get('/zoom/callback', async (request, reply) => {
    return handleCallback(request, reply);
  });
  fastify.get('/auth/zoom/callback', async (request, reply) => {
    return handleCallback(request, reply);
  });

  async function handleCallback(request: any, reply: any) {
    const query = request.query as { code?: string; state?: string; error?: string };

    if (query.error) {
      log.warn({ error: query.error }, 'User declined Zoom authorization');
      return reply.type('text/html').send(`
        <!DOCTYPE html>
        <html>
        <head><title>Authorization Cancelled</title></head>
        <body style="font-family: sans-serif; text-align: center; padding: 50px; background: #0f172a; color: #f8fafc;">
          <h2>❌ Authorization Cancelled</h2>
          <p>You declined the Zoom authorization. You can close this tab and return to Telegram.</p>
        </body>
        </html>
      `);
    }

    if (!query.code || !query.state) {
      return reply.status(400).send('Missing authorization code or state parameter');
    }

    // OAuth `state` is a CSRF token and must have been generated by us.
    let telegramUserId: bigint | null = null;
    try {
      telegramUserId = await oauthStateRepo.consumeAndDelete(query.state);
    } catch {
      telegramUserId = null;
    }

    if (!telegramUserId) {
      log.warn({ state: query.state }, 'Invalid or expired OAuth state parameter');
      return reply.status(400).send('Invalid or expired state parameter. Please try clicking Connect Zoom again from Telegram.');
    }

    try {
      const clientId = process.env['ZOOM_CLIENT_ID'] ?? '';
      const clientSecret = process.env['ZOOM_CLIENT_SECRET'] ?? '';
      const redirectUri =
        process.env['ZOOM_REDIRECT_URI'] ?? 'https://ai-zoom-participant.onrender.com/auth/zoom/callback';
      const encryptionKey = process.env['ENCRYPTION_KEY'];
      if (!encryptionKey) {
        throw new Error('ENCRYPTION_KEY must be configured before connecting a Zoom account');
      }

      // Exchange code for tokens
      const tokenResp = await exchangeCodeForTokens(
        query.code,
        clientId,
        clientSecret,
        redirectUri,
      );

      // Get Zoom user profile
      const profile = await getZoomUserProfile(tokenResp.access_token);

      // Upsert user in database
      const user = await userRepo.upsert(telegramUserId);

      // Encrypt tokens
      const accessTokenEncrypted = encryptToken(tokenResp.access_token, encryptionKey);
      const refreshTokenEncrypted = encryptToken(tokenResp.refresh_token, encryptionKey);
      const tokenExpiresAt = new Date(Date.now() + tokenResp.expires_in * 1000);

      // Store tokens
      await zoomAccountRepo.storeTokens({
        userId: user.id,
        zoomUserId: profile.id,
        zoomEmail: profile.email,
        accessTokenEncrypted,
        refreshTokenEncrypted,
        tokenExpiresAt,
        scopes: tokenResp.scope,
      });

      await auditRepo.log({
        userId: user.id,
        action: 'ZOOM_OAUTH_CONNECTED',
        metadata: { zoomUserId: profile.id, email: profile.email },
      }).catch(() => {});

      log.info({ userId: user.id, zoomEmail: profile.email }, 'Zoom account successfully connected');

      return reply.type('text/html').send(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>Zoom Connected!</title>
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; text-align: center; padding: 40px 20px; background: #0f172a; color: #f8fafc; }
            .card { max-width: 400px; margin: 0 auto; background: #1e293b; padding: 30px; border-radius: 16px; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }
            h2 { color: #38bdf8; margin-bottom: 10px; }
            p { color: #94a3b8; font-size: 15px; }
            .email { background: #334155; padding: 8px 16px; border-radius: 8px; font-family: monospace; color: #e2e8f0; display: inline-block; margin: 15px 0; }
          </style>
        </head>
        <body>
          <div class="card">
            <h2>✅ Zoom Connected!</h2>
            <p>Your Zoom account has been successfully linked:</p>
            <div class="email">${profile.email}</div>
            <p>You can close this tab and return to Telegram to manage your Zoom meetings.</p>
          </div>
        </body>
        </html>
      `);
    } catch (err: any) {
      const errMsg = err?.message || String(err);
      log.error({ error: errMsg }, 'OAuth callback handler error');
      return reply.status(200).type('text/html').send(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>Zoom Connection Error</title>
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; text-align: center; padding: 40px 20px; background: #0f172a; color: #f8fafc; }
            .card { max-width: 440px; margin: 0 auto; background: #1e293b; padding: 30px; border-radius: 16px; box-shadow: 0 10px 25px rgba(0,0,0,0.5); border: 1px solid #ef4444; }
            h2 { color: #f87171; margin-bottom: 10px; }
            p { color: #94a3b8; font-size: 14px; line-height: 1.5; }
            .err { background: #451a1a; padding: 12px; border-radius: 8px; font-family: monospace; color: #fca5a5; display: block; margin: 15px 0; word-break: break-all; text-align: left; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="card">
            <h2>⚠️ Authorization Error</h2>
            <p>Could not complete Zoom OAuth token exchange:</p>
            <div class="err">${errMsg}</div>
            <p>Please ensure <code>ZOOM_CLIENT_ID</code> and <code>ZOOM_CLIENT_SECRET</code> on Render match your Zoom Marketplace app, and try clicking Connect Zoom again from Telegram.</p>
          </div>
        </body>
        </html>
      `);
    }
  }
};
